name: Build and Push Singularity Image

on:
  push:
    branches:
      - hpc-compatible
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: X86
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Singularity setup
        uses: singularityhub/install-singularity@main

      - name: Import Singularity private key
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > private.key
          singularity key import private.key
          rm private.key

      - name: Build Singularity Image
        run: |
            singularity build ciroh-ngen-visualizer-singularity.sif singularity_tethys_ngiab.def

      - name: Sign the image
        run: |
          echo "${{ secrets.KEY_PASSPHRASE }}" > pass.txt
          singularity sign --keyidx 1 --passphrase-file pass.txt ciroh-ngen-visualizer-singularity.sif
          rm pass.txt

      - name: Login and Push Singularity Image
        env:
           SYLABS_AUTH_TOKEN: ${{ secrets.SYLABS_AUTH_TOKEN }}
        run: |
           # Debug: Check token length (don't print the actual token)
           echo "Token length: ${#SYLABS_AUTH_TOKEN}"
        
           # Create a temporary file for the token
           TOKEN_FILE=$(mktemp)
           echo "$SYLABS_AUTH_TOKEN" > "$TOKEN_FILE"
        
           # Debug: Check file content length
           echo "Token file content length: $(wc -c < "$TOKEN_FILE")"
        
           # Attempt to login
           if singularity remote login --tokenfile "$TOKEN_FILE"; then
              echo "Login successful"
              # Delete existing image and Push the image
              singularity delete --force library://gioelkin/ngiab/ciroh-ngen-visualizer-singularity:latest_x86
              singularity push ciroh-ngen-singularity.sif library://gioelkin/ngiab/ciroh-ngen-visualizer-singularity:latest_x86
           else
              echo "Login failed"
              exit 1
           fi
        
           # Clean up
           rm "$TOKEN_FILE"