name: Build and Push Singularity Image

on:
  push:
    branches:
      - hpc-compatible
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Singularity setup
      #   uses: singularityhub/install-singularity@main

      # - name: Import Singularity private key
      #   env:
      #     KEY_B64: ${{ secrets.SIGNING_KEY }}
      #     KEY_PASS: ${{ secrets.KEY_PASSPHRASE }}
      #   run: |
      #     echo "$KEY_B64" | base64 -d > private.asc
      #     echo "$KEY_PASS" > passphrase.txt
      #     singularity key import --passphrase-file passphrase.txt private.asc
      #     rm -f private.asc passphrase.txt

      # - name: Sign the image
      #   run: |
      #     echo "${{ secrets.KEY_PASSPHRASE }}" > pass.txt
      #     singularity sign --keyidx 1 --passphrase-file pass.txt ciroh-ngen-visualizer-singularity.sif
      #     rm pass.txt




      - name: Set up Go
        uses: actions/setup-go@v5
        id: go

      - name: Install Dependencies
        if: ${{ env.keepgoing == 'true' }}
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            pkg-config \
            debootstrap

      - name: Install Singularity
        env:
          SINGULARITY_VERSION: 4.2.0
          GOPATH: /tmp/go
      
        run: |
          mkdir -p $GOPATH
          sudo mkdir -p /usr/local/var/singularity/mnt && \
          mkdir -p $GOPATH/src/github.com/sylabs && \
          cd $GOPATH/src/github.com/sylabs && \
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz | \
          tar xzv && \
          cd singularity-ce-${SINGULARITY_VERSION} && \
          ./mconfig -p /usr/local && \
          make -C builddir && \
          sudo make -C builddir install          


      - name: Build Singularity Image
        run: |
            sudo -E singularity build ciroh-ngen-visualizer-singularity.sif singularity_tethys_ngiab.def
            
      - name: Login and Push Singularity Image
        env:
           SYLABS_AUTH_TOKEN: ${{ secrets.SYLABS_AUTH_TOKEN }}
        run: |
           # Debug: Check token length (don't print the actual token)
           echo "Token length: ${#SYLABS_AUTH_TOKEN}"
        
           # Create a temporary file for the token
           TOKEN_FILE=$(mktemp)
           echo "$SYLABS_AUTH_TOKEN" > "$TOKEN_FILE"
        
           # Debug: Check file content length
           echo "Token file content length: $(wc -c < "$TOKEN_FILE")"
        
           # Attempt to login
           if singularity remote login --tokenfile "$TOKEN_FILE"; then
              echo "Login successful"
              # Delete existing image and Push the image
              singularity delete --force library://gioelkin/ngiab/ciroh-ngen-visualizer-singularity:latest_x86
              singularity push ciroh-ngen-singularity.sif library://gioelkin/ngiab/ciroh-ngen-visualizer-singularity:latest_x86
           else
              echo "Login failed"
              exit 1
           fi
        
           # Clean up
           rm "$TOKEN_FILE"